name: lab10-workflow-stepcd
on: workflow_dispatch
jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      - name: Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: djkrnl/zad2gitops:v1
          cache-from: type=registry,ref=scoutertf2/zad2gitops:v1
          cache-to: type=inline